name: 'GitHub Actions  Email Bot'

on:
  push:
    
jobs:
 bot:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: 'Send mail'
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: SUSDLWJFZZXHQFCJ
        subject: 林舒仪
        body: 林舒仪的action记录
        to: zwzvv@163.com
        from: linshuyiaa00@163.com
        content_type: text/plain
