name: 'Send emailto the teacher'

on:
  push:
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 林舒仪的GitHub Actions
          body: ${{github.repository}} 的构建作业成功完成！
          to: 2044339693@qq.com
          from: 418008503@qq.com
          